name: fluttersnap_inventory
description: A Flutter inventory app
publish_to: "none"

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.3
  firebase_database: ^10.4.5
  intl: ^0.19.0
