// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_KbKuL5flSNeCQYjD_kwt17afs2jltfM',
    appId: '1:789274744362:web:10e7d322e6634604575553',
    messagingSenderId: '789274744362',
    projectId: 'fluttersnap-inventory-2fb87',
    authDomain: 'fluttersnap-inventory-2fb87.firebaseapp.com',
    storageBucket: 'fluttersnap-inventory-2fb87.firebasestorage.app',
    measurementId: 'G-JML80WCQG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBFnKIk3PO_PFXPE_dcrmyv-xWj05boSg',
    appId: '1:789274744362:android:11bd8b99b4b0326f575553',
    messagingSenderId: '789274744362',
    projectId: 'fluttersnap-inventory-2fb87',
    storageBucket: 'fluttersnap-inventory-2fb87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDglb_KJJVK-afSvSw_7lT0aFUU0jrjCNI',
    appId: '1:789274744362:ios:0262331688d22d8d575553',
    messagingSenderId: '789274744362',
    projectId: 'fluttersnap-inventory-2fb87',
    storageBucket: 'fluttersnap-inventory-2fb87.firebasestorage.app',
    iosBundleId: 'com.example.fluttersnapInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDglb_KJJVK-afSvSw_7lT0aFUU0jrjCNI',
    appId: '1:789274744362:ios:0262331688d22d8d575553',
    messagingSenderId: '789274744362',
    projectId: 'fluttersnap-inventory-2fb87',
    storageBucket: 'fluttersnap-inventory-2fb87.firebasestorage.app',
    iosBundleId: 'com.example.fluttersnapInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_KbKuL5flSNeCQYjD_kwt17afs2jltfM',
    appId: '1:789274744362:web:6662fa5d9af9ec18575553',
    messagingSenderId: '789274744362',
    projectId: 'fluttersnap-inventory-2fb87',
    authDomain: 'fluttersnap-inventory-2fb87.firebaseapp.com',
    storageBucket: 'fluttersnap-inventory-2fb87.firebasestorage.app',
    measurementId: 'G-RVN00PKYHF',
  );
}
